name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./KeychainStore
      run: swift build -v
    - name: Run tests
      working-directory: ./KeychainStore
      run: swift test -v
